export const SET_CURRENT_MOVIES = 'SET_CURRENT_MOVIES'
export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES'
export const SET_UPCOMING_MOVIES = 'SET_UPCOMING_MOVIES'
export const SET_TOP_MOVIES = 'SET_TOP_MOVIES'
export const SET_SIMILAR_MOVIES = 'SET_SIMILAR_MOVIES'

export const SET_CURRENT_SHOWS = 'SET_CURRENT_SHOWS'
export const SET_POPULAR_SHOWS = 'SET_POPULAR_SHOWS'
export const SET_AIRING_TODAY_SHOWS = 'SET_AIRING_TODAY_SHOWS'
export const SET_TOP_SHOWS = 'SET_TOP_SHOWS'
export const SET_SIMILAR_SHOWS = 'SET_SIMILAR_SHOWS'
export const SET_LATEST = 'SET_LATEST'

export const SET_ITEM_TYPE = 'SET_ITEM_TYPE'
export const SET_QUERY_ITEM = 'SET_QUERY_ITEM'
export const SET_QUERY_ITEM_DETAILS = 'SET_QUERY_ITEM_DETAILS'
export const SET_QUERY_ITEM_VIDEOS = 'SET_QUERY_ITEM_VIDEOS'

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH'


export const SET_ERROR = 'SET_ERROR'
