export const SET_CURRENT_MOVIES = 'SET_CURRENT_MOVIES'
export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES'
export const SET_UPCOMING_MOVIES = 'SET_UPCOMING_MOVIES'
export const SET_TOP_MOVIES = 'SET_TOP_MOVIES'

export const SET_CURRENT_SHOWS = 'SET_CURRENT_SHOWS'
export const SET_POPULAR_SHOWS = 'SET_POPULAR_SHOWS'
export const SET_AIRING_TODAY_SHOWS = 'SET_AIRING_TODAY_SHOWS'
export const SET_TOP_SHOWS = 'SET_TOP_SHOWS'

export const SET_ITEM_TYPE = 'SET_ITEM_TYPE'
export const SET_QUERY_ITEM = 'SET_QUERY_ITEM'
export const SET_QUERY_ITEM_DETAILS = 'SET_QUERY_ITEM_DETAILS'
export const SET_QUERY_ITEM_VIDEOS = 'SET_QUERY_ITEM_VIDEOS'
export const SET_SIMILAR_ITEMS = 'SET_SIMILAR_ITEMS'
export const SET_ITEM_CLEAR = 'SET_ITEM_CLEAR'

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH'

export const FETCH_FAVORITE_LIST_SUCCESS = 'FETCH_FAVORITE_LIST_SUCCESS'
export const FETCH_WATCH_LATER_LIST_SUCCESS = 'FETCH_WATCH_LATER_LIST_SUCCESS'

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'

export const SET_DISCOVER_MOVIE_RESULTS = 'SET_DISCOVER_MOVIE_RESULTS'
export const SET_DISCOVER_SHOW_RESULTS = 'SET_DISCOVER_SHOW_RESULTS'

export const SET_ERROR = 'SET_ERROR'
